from fastapi import FastAPI, UploadFile

from invoice import extract_invoice
from to_csv import json_to_csv

app = FastAPI()


@app.get("/")
def read_root():
    return {"Sanity": "Check"}


@app.post("/uploadfile/")
async def create_upload_file(file: UploadFile):
    data = extract_invoice(file.file).replace('\n', '').replace("'", '"')
    json_to_csv(data)

    return {"data": data}


# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uv9FsKfBLLFkT1eBLsqIYKi9ZALJBEY
"""



#pip install transformers
import pandas as pd
from transformers import pipeline
import os
import requests

model_checkpoint = "huggingface-course/bert-finetuned-ner"
token_classifier = pipeline(
    "token-classification", model=model_checkpoint, aggregation_strategy="simple"
)

def split_on_and(input_string):
    split_words = input_string.split('and')
    words_before = split_words[0].strip().split()
    word_before = words_before[-1] if words_before else ''
    word_after = split_words[1].strip().split()[0] if len(split_words) > 1 else ''
    return word_before, word_after


def get_highest_objects(string, data,df):
    highest_score = -1
    highest_org = None

    for item in data:
        if (item['entity_group'] == 'ORG' or item['entity_group'] == 'PER' )  and item['score'] > highest_score:
            highest_score = item['score']
            highest_org = "Place equals " + item['word']
    for item in data:
        if item['entity_group'] == 'LOC' and item['score'] > highest_score:
            highest_score = item['score']
            highest_loc = item['word']
            highest_loc = "Address contains " + highest_loc
    word_before, word_after = split_on_and(string)
    prompt = f"write a function called generated_function that returns two lists of the values {word_before} {word_after} columns from inputed dataframe df where {highest_org}"
    print(prompt)
    return prompt

def prompt(insert_prompt):
    CODEPAL_API_KEY = 'f796e543-5b48-4476-b8bb-3da3c6e3fee4'
    headers = {
        # Already added when you pass json= but not when you pass data=
        # 'Content-Type': 'application/json',
        'Authorization': f"Bearer {CODEPAL_API_KEY}",
    }
    print(headers)
    files = {
    'language': (None, 'python'),
    'instructions': (None, insert_prompt),
    }
    response = requests.post('https://api.codepal.ai/v1/code-generator/query', headers=headers, files=files)
    result = response.json()
    print(result)
    return result

def write_to_py_file(string):
  text_file = open("function1.py", "w")
  n = text_file.write(string)
  text_file.close()

string = "Plot Date and Total I spent at Walgreens?"
data = token_classifier(string)
df = pd.read_csv('./Structured_Data.csv')
insert_prompt  = get_highest_objects(string, data,df)
print(insert_prompt)
run_Prompt = prompt(insert_prompt)
resulting_prompt= run_Prompt['result']
write_to_py_file(resulting_prompt)
from function1 import generated_function
x,y  = generated_function(df)

print(x)
print(y)



