# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M5n3-w3pKz-nlH3YohG7ATHI7YYAPJeB
"""

# Note: json_data will not be serialized by requests
# exactly as it was in the original request.
#data = '{\n     "instructions": "prints the sum of two numbers",\n     "language": "python"\n   }'
#response = requests.post('https://api.codepal.ai/v1/code-generator/query', headers=headers, data=data)

def prompt(x,y,criterion,dataframe):
    CODEPAL_API_KEY = 'e06664cf-63cd-4103-97a4-aea50a1e7c3d'
    headers = {
        # Already added when you pass json= but not when you pass data=
        # 'Content-Type': 'application/json',
        'Authorization': f"Bearer {CODEPAL_API_KEY}",
    }
    print(headers)
    files = {
    'language': (None, 'python'),
    'instructions': (None, f'"write a function that returns two lists of the values {x} {y} columns from {dataframe} where {criterion} "'),
    }
    response = requests.post('https://api.codepal.ai/v1/code-generator/query', headers=headers, files=files)
    result = response.json()
    print(result)
    return result

def write_to_py_file(string):
  text_file = open("function1.py", "w")
  n = text_file.write(string)
  text_file.close()

df = pd.read_csv('/content/Hackathon data.csv')
run_Prompt = prompt("Date","Total","Place is Starbucks",df)
resulting_prompt= run_Prompt['result']
from function1 import get_date_total_lists
write_to_py_file(resulting_prompt)